// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqxjtznrdjkksoitcnmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxeGp0em5yZGpra3NvaXRjbm1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTEyNDQsImV4cCI6MjA2OTg2NzI0NH0.3iEVSrmORUB6kN3tk3-KzH1g1MwSqVVqkyLrT6VFGjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});